To-do List:
#+SEQ_TODO: BUG TODO TEST WISH

* Sujeet Gholap
* Devesh Y
* Guru P
* S. Pradeep Kumar
** TODO (?) Setting both players to AGGRESSIVE makes the game run really really long, which means, of course, that the game can't be displayed, etc.
** WISH Display a blast when bullets collide
** Documentation
** Note : Since, we're calling the same functions for Machine Gun as for Tank, all sorts of stuff is done for Machine Guns. eg. Its score gets updated. Just fyi
** BUG Check validity of submission
** BUG Check whether submission takes too long to compute stuff
** Machine guns shoot unidirectionally
** TODO Moving machine guns			:ARCHIVE:
*** Bundle DecisionMaker along with each Machine gun, so that they can make their own decisions
*** TODO Take care that they don't eat up the Gold, hit the falcon or do anything like that
*** Tower MG - T - shoot if a tank is within a certain square
*** Have some MGs just stay in one position and shoot unidirectionally to trap some Tank
** Wall around falcon
** Some simple maps for the finals (?)
** Maps
*** Gold rush
*** Rush to the top
*** Cities (?)
*** Traps
*** Gold-less map
