To-do List:
#+SEQ_TODO: BUG TODO TEST

* Sujeet Gholap
* Devesh Y
* Guru P
* S. Pradeep Kumar
** Function initialize_from in Tank.h should take an ID preferably
** Use Tank's ID everywhere
** TEST Tank crossing, Bullet crossing condition
** TODO Do stuff when the game gets over
*** Increment the score of the surviving players, etc.
** Random SegFault occurring from time to time
** Consider increasing the speed of bullets
** Display a blast when bullets collide
** Note : Since, we're calling the same functions for Machine Gun as for Tank, all sorts of stuff is done for Machine Guns. eg. Its score gets updated. Just fyi
** TODO Decide upon the Points Allocation
** BUG Tank Bullet cross kills the tank, but the bullet is shown in the new position
** TODO Have function to see if you can shoot E.Falcon/E.Tank
** Testing
** Server
** Documentation
** Create folders obj/ and output/ by default. make play gives an error otherwise
** Have a lookup table below or next to the display of the map, so that we can easily identify which coloured square corresponds to which object, eg. Tank, Machine Gun, etc.
** TODO Dammit! Have a space before and after every paren [, (, ), ], and all the usual operators
** There is a bit of an ambiguity when two tanks are very close to each other. If one shoots the other at point-blank range, the other tank dies, but it isn't obvious why.
** In a long game, if I press Faster twice or thrice, the game hangs. If I press Slower 10 seconds later, the game resumes but from a state which is that many moves ahead. As in, it skips moves. 
