To-do List:
#+SEQ_TODO: BUG TODO TEST

* Sujeet Gholap
* Devesh Y
* Guru P
* S. Pradeep Kumar
** BUG (?) Setting both players to AGGRESSIVE makes the game run really really long, which means, of course, that the game can't be displayed, etc.
** BUG Tank Bullet cross kills the tank, but the bullet is shown in the new position
** Consider increasing the speed of bullets
** TODO Create folders obj/ and output/ by default. make play gives an error otherwise
** Display a blast when bullets collide
** Documentation
** Function initialize_from in Tank.h should take an ID preferably
** Have a lookup table below or next to the display of the map, so that we can easily identify which coloured square corresponds to which object, eg. Tank, Machine Gun, etc.
** In a long game, if I press Faster twice or thrice, the game hangs. If I press Slower 10 seconds later, the game resumes but from a state which is that many moves ahead. As in, it skips moves. 
** Note : Since, we're calling the same functions for Machine Gun as for Tank, all sorts of stuff is done for Machine Guns. eg. Its score gets updated. Just fyi
** Random SegFault occurring from time to time
** TEST Tank crossing, Bullet crossing condition
** TODO Check validity of submission
** TODO Check whether submission takes too long to compute stuff
** TODO Dammit! Have a space before and after every paren [, (, ), ], and all the usual operators
** Testing
** There is a bit of an ambiguity when two tanks are very close to each other. If one shoots the other at point-blank range, the other tank dies, but it isn't obvious why.
** Machine guns shoot unidirectionally
** TODO Moving machine guns
*** Make dead machine guns disappear
*** Bundle DecisionMaker along with each Machine gun, so that they can make their own decisions
*** Take care that they don't eat up the Gold, hit the falcon or do anything like that
*** Dashing against each other - ok?
*** Make an update_machine_guns_on_map function as part of Arena, which will update machine guns and kill dead ones
*** Have some MGs defend a particular area - call them D
*** Have some MGs go and pursue Tanks - call them P
*** Have some MGs try to intercept Tanks - call them I
*** Have some MGs just stay in one position and shoot unidirectionally to trap some Tank
** Wall around falcon
** Some simple maps for the finals (?)
** Maps
*** Gold rush
*** Rush to the top
*** Cities (?)
*** Traps
*** Gold-less map
