To-do List:
#+SEQ_TODO: BUG TODO TEST WISH

* Sujeet Gholap
* Devesh Y
* Guru P
* S. Pradeep Kumar
** BUG Have a proper scoring mechanism - so that people whose games get over early don't suffer
** BUG The zip file should have a folder called Tank-Wars inside which everything else is present. Right now it just puts everything into the same folder as the zip file.
** Maps								    :ARCHIVE:
*** Gold rush
*** Rush to the top
*** Cities (?)
*** Traps
*** Gold-less map
*** Wall around falcon
*** Some simple maps for the finals (?)
** BUG I've made bullets get updated after get_player_move
*** Otherwise, the bullet list the players get will be the updated bullet list
*** Which is kinda confusing
*** So, peace!
** TODO Machine Guns						    :ARCHIVE:
*** Machine guns shoot unidirectionally
*** TODO Moving machine guns			:ARCHIVE:
*** Bundle DecisionMaker along with each Machine gun, so that they can make their own decisions
*** TODO Take care that they don't eat up the Gold, hit the falcon or do anything like that
*** Tower MG - T - shoot if a tank is within a certain square
*** Have some MGs just stay in one position and shoot unidirectionally to trap some Tank
** WISH Display a blast when bullets collide	:ARCHIVE:
** Note : Since, we're calling the same functions for Machine Gun as for Tank, all sorts of stuff is done for Machine Guns. eg. Its score gets updated. Just fyi :ARCHIVE:
** Make the Move counter show current move number / BULLET_SPEED in Arena
** Something to indicate that the Falcon was killed
** Maybe display 'Tank 1 has won!!
